<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Try another way</name>
   <tag></tag>
   <elementGuidId>bcc9bd00-16ef-4ce9-b6a0-49fec4f313aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='tryanotherway']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;tryanotherway&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3de08a82-8930-4abd-8fd9-1551e626097a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>579e5a81-1238-43f5-9cf2-f26da1e543a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 _al4m _4jy6 _517h _51sy</value>
      <webElementGuid>557fb495-8c15-4fba-b66c-381b2513d85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tryanotherway</value>
      <webElementGuid>9ae20a52-35c9-400c-9888-3602ca69c523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/recover/initiate/?is_from_lara_screen=1</value>
      <webElementGuid>b94771b4-94c1-4c30-bcfb-8a5b61485938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Try another way</value>
      <webElementGuid>374f1f1e-6a17-419f-abef-aac73be751a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginform&quot;)/div[@class=&quot;_xkt&quot;]/a[@class=&quot;_42ft _4jy0 _al4m _4jy6 _517h _51sy&quot;]</value>
      <webElementGuid>f2548cd1-4385-48f3-89b5-0a1fa2080348</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='tryanotherway']</value>
      <webElementGuid>75ab806c-cd08-4604-957e-c015d82c4a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginform']/div[3]/a</value>
      <webElementGuid>45f30bf2-03d4-43f4-b070-a7f2112c3e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Try another way')]</value>
      <webElementGuid>f9b91250-a3ed-469a-af9b-3badfdebcf8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/recover/initiate/?is_from_lara_screen=1')]</value>
      <webElementGuid>b783e5e7-f612-447e-a2b9-067f1ebc1fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>65f2e13c-a0dd-46dd-a499-69ad42b300d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'tryanotherway' and @href = '/recover/initiate/?is_from_lara_screen=1' and (text() = 'Try another way' or . = 'Try another way')]</value>
      <webElementGuid>d7aa66cc-e2ea-457c-a5a1-0d1873993c07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
