<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>ea5d94e1-b8a6-4609-b026-583ea5413523</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='reset_action']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;reset_action&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd06fd25-dcf0-44ec-8d8a-92f1fd79a662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ad362211-0373-493c-9ea3-3d13fffe2703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 _9nq0 textPadding20px _4jy3 _4jy1 selected _51sy</value>
      <webElementGuid>7c592a0b-64eb-495a-b0f5-39d996d3a0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reset_action</value>
      <webElementGuid>6876bdc4-c531-4c8b-ae88-95c84089b8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>aef8003f-647a-48e8-b938-60c89101358a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>641ddb86-d906-4021-a692-14d19a5e8a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;initiate_interstitial&quot;)/div[@class=&quot;uiInterstitialBar uiBoxGray topborder&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;rfloat _ohf&quot;]/button[@class=&quot;_42ft _4jy0 _9nq0 textPadding20px _4jy3 _4jy1 selected _51sy&quot;]</value>
      <webElementGuid>346cec62-4fa9-46fb-a6ab-6f24ff5b11e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='reset_action']</value>
      <webElementGuid>f603bfea-abfe-4d00-93db-c00c6652805d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='initiate_interstitial']/div[3]/div/div/button</value>
      <webElementGuid>922e05f6-2b13-41b9-8f82-9ba5a6275a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>025fb963-8475-4fe1-95ab-0caeb58274c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'reset_action' and @type = 'submit' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>9fcc5061-3aaa-4e8d-8718-3845753b0446</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
